require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - "db/migrate/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "config/initializers/**/*"
    - "vendor/**/*"
RSpec/MultipleExpectations:
  Max: 2
RSpec/ExampleLength:
  Max: 10
Hc/RailsSpecificActionName:
  Exclude:
    - "app/controllers/api/v1/retweets_controller.rb"
    - "app/controllers/api/v1/favorites_controller.rb"
