require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
  - rubocop-factory_bot
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - "db/migrate/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "config/initializers/**/*"
RSpec/MultipleExpectations:
  Max: 2
